import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import tratamiento from '@/lib/tratamiento'
import TablaPrueba from '@/lib/TablaPrueba'
import TablaComunes from '@/lib/tablaComunes'
import Cookies from 'js-cookie'
import { parseCookies } from 'nookies'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [query, setQuery] = useState([])
  const [results, setResult] = useState([])
  const [info, setInfo] = useState([]) 
  const [comunes, setComunes] = useState([])
  
  
  //console.log(api)


  async function manejarInformacionTabla(data){
    console.log("Lo que envia al hacer click",data);

    const consulta  = data[2].map( e =>( {friend_since: e.friend_since, id64: e.steamid}))

    const infoAmpliada = await fetch('/api/getInfoPlayers', {
      method: 'POST',
      body: JSON.stringify(consulta),
      headers: {
        "Content-Type": "application/json"
      }
    })

    const infoComunes = await infoAmpliada.json();

    console.log(infoComunes);

    const elementos = [];

    // const elementosComunes =  infoComunes.map( (e,i) => {
    //   e.data.map( (jug,ind) => {
    //       var desde;
    //       jug.forEach(elem => {

    //       })
    //       jug.since = e.since[ind+100*i]
    //       elementos[ind + 100 * i] = {data: jug}
    //   })
    // })

    console.log("Elementos comunes", elementos)
    console.log("Infocomunes",infoComunes)

    setComunes([data[0],data[1],infoComunes]);
  }

  async function handleSubmit (e) {
    e.preventDefault()

    const busqueda = query.map( e=> {return {id64:e.steamid64, friend_since: 0}});

    const infoplayers = await fetch('/api/getInfoPlayers', {
      method: 'POST',
      body: JSON.stringify(busqueda),
      headers: {
        "Content-Type": "application/json"
      }
    })

    const infoplayerJson = await infoplayers.json();

    console.log("infoplayerJson",infoplayerJson)

    setInfo(infoplayerJson)

    const res = await fetch('/api/friendsList', {
      method: 'POST',
      body: JSON.stringify(busqueda),
      headers: {
        "Content-Type": "application/json"
      }
    })
    const data = await res.json();
    console.log(data)
    setResult(data)
  }
  return (
    <>
      <Head>
        <title>Buscador Amigos Comunes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/friendsapp.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.input}>
            <div className={styles.header}>
              <form onSubmit={handleSubmit} className={styles.formulario}>

                <input
                className={styles.textoInput}
                  type="text"
                  value={
                    query.length > 0 ? (query.length + " Jugadores detectados") : ("Status consola")
                  }
                  onChange={e => setQuery( tratamiento(e.target.value) )}
                />
                <button type="submit" className={styles.buscar}>Buscar</button>
              </form>
            </div>
            
        
      {/* {info.length > 0 ? (<h2 style={{textAlign: "center", margin: "20px 0 5px 0"}}>Tabla de amigos</h2>): (<></>)} */}
      <div className={styles.tabla}>
        <TablaPrueba info={[info, results]} onData={manejarInformacionTabla} />
        <TablaComunes info={comunes} />
      </div>
      
      </div>
        </div>
      </main>
    </>
  )
}
